name: Hello
main: com.jack.hello.Hello
version: 1.0
commands:
  heal:
    description: Heal command
  sethome:
    description: Set home command
  delhome:
    description: Delete home command
  home:
    description: Home command