name: Hello
main: com.jack.hello.Hello
version: 1.0
commands:
  heal:
    description: Heals a player
  sethome:
    description: Sets a player's home
  delhome:
    description: Deletes a player's home
  home:
    description: Teleports a player to their home
  listhomes:
    description: Lists all homes of a player